---
title: "CE Exploration"
format: pdf
editor: visual
---

## Senior Thesis - Data Exploration

```{r, warning= FALSE, message = FALSE}
# Load packages
if (!require(survey)) install.packages("survey"); library(survey)
if (!require(tidyverse)) install.packages("tidyverse"); library(tidyverse)
if (!require(rpms)) install.packages("rpms"); library(rpms)
if (!require(sampling)) install.packages("sampling"); library(sampling)
if (!require(ipumsr)) install.packages("ipumsr"); library(ipumsr)
if (!require(cpsR)) install.packages("cpsR"); library(cpsR)
if (!require(NHANES)) install.packages("NHANES"); library(NHANES)
```

### CE Dataset

```{r}
ce = CE # %>% filter(TOTEXPCQ > 0 & FINCBTAX > 0)
summary(ce$FINLWT21)

# Overpopulating South Region
table(ce$REGION)

# Oversampling largest population size!!
table(ce$POPSIZE)

weird = ce %>% slice_min(FINLWT21, n = 5)
```

```{r}
# Quick Linear Regressions
basic <- lm(FINCBTAX ~ TOTEXPCQ, data = ce)
summary(basic)

plot(basic) # Very Yucky :(

ggplot(ce, aes(x = log(TOTEXPCQ), y = log(FINCBTAX))) +
  geom_point(alpha = 0.1) + 
  geom_smooth(method = "lm")
```

```{r}
ggplot(ce, aes(TOTEXPCQ)) + geom_histogram()
ggplot(ce, aes(log(TOTEXPCQ))) + geom_histogram()

ggplot(ce, aes(FINCBTAX)) + geom_histogram()
ggplot(ce, aes(log(FINCBTAX))) + geom_histogram()
```

```{r}
transformed <- lm(log(FINCBTAX + 0.001) ~ log(TOTEXPCQ + 0.001),
                  data = ce)
summary(transformed)

plot(transformed)
```

```{r}
summary(ce$STATE) # Missing 8473
summary(ce$REGION) # Missing 1430
summary(ce$POPSIZE) # Only missing 215 out of 68,415
summary(ce$PSU) # Over half are missing
```

```{r}
ce_filtered = ce %>%
  filter(TOTEXPCQ > 0 & FINCBTAX > 0)

ggplot(ce_filtered, aes(log(TOTEXPCQ), log(FINCBTAX))) + # 41524 observations
  geom_point(alpha = 0.1) + 
  geom_smooth(method = "lm") #+ 
  #facet_wrap(vars(EARNTYPE))

table(CE$EARNTYPE)

test = lm(log(FINCBTAX) ~ log(TOTEXPCQ), ce_filtered) # R^2 of 0.2919
summary(test)
```

```{r}
CE %>% summarise_all(~sum(is.na(.)))

ce_test = CE %>%
  filter(TOTXEST > 0 & SALARYX < 400000 & TOTEXPCQ > 0 & FINCBTAX > 0) # R^2 is 0.4279 if salary < 200000

test = lm(log(SALARYX) ~ log(TOTXEST), ce_test)
summary(test) # R^2 of 0.5033

ggplot(ce_test, aes(log(TOTXEST), log(SALARYX))) + # 17734 observations
  geom_point(alpha = 0.05) + 
  geom_smooth(method = "lm")
```

```{r}
library(corrplot)
cor_df = ce %>% 
      select(FINCBTAX, SALARYX,
             SOCRRX, IRAX, #LIQUIDX, STOCKX, STUDNTX,
             TOTEXPCQ, TOTXEST, EHOUSNGC,
             HEALTHCQ, FOODCQ, TOBACCCQ, FOOTWRCQ) %>% drop_na()

cor(cor_df)

corrplot(cor(cor_df))
```

```{r}
ce = CE |> filter(TOTEXPCQ > 0 & FINCBTAX > 0 & IRAX > 0)

ggplot(ce, aes(x = log(IRAX), y = log(FINCBTAX))) + 
  geom_point(alpha = 0.08) + 
  geom_smooth(method = "lm")

ggplot(ce, aes(x = log(TOTEXPCQ), y = log(FINCBTAX))) + 
  geom_point(alpha = 0.08) + 
  geom_smooth(method = "lm") + 
  facet_grid(EARNTYPE ~ .)
```

### API

```{r}
# Simple data visuals and regression

data(api)

ggplot(apipop, aes(api99, api00)) + 
  geom_point() + 
  geom_smooth(method = "lm") + 
  geom_abline(slope = 1, intercept = 0, color = "red")


lm1 = lm(api00 ~ api99, data = apipop)
summary(lm1)
```
```{r}
table(apipop$cnum) # Good to use strata and cluster from!
table(apipop$dnum)
```

```{r}
# Clean data
api = apipop |>
  select(cds, stype, name, snum, dnum, cnum, pcttest, api00, api99,
         meals, ell, mobility, avg.ed, full, enroll, api.stu)


filter(api, is.na(avg.ed))

summary(apipop$col.grad)


summary(api)
```

### NHANES

```{r}
ggplot(filter(NHANES, Weight < 50), aes(x = Weight, y = Height)) + 
  geom_point() + 
  geom_smooth(method = "lm")

filter(NHANES, Weight < 50)


```

