---
title: "Methods"
format: pdf
editor: visual
---

## Methods

Simulation studies are widely used in survey statistics to evaluate the performance of different sampling methods and designs under various scenarios. Testing survey weight diagnostic tests requires simulating data under different conditions continuously. The few simulation studies to test the performance of several diagnostic tests either used purely simulated data or existing survey data then alter the selection probabilities by using the survey data as the population to survey from.

The data generating process for this simulation study will utilize existing survey data from the Bureau of Labor Statistics' Consumer Expenditure Survey public use interview data file. The dataset for 2015 contains consumer unit characteristics, assets, and expenditure data for consumers in the United States collected by the Census Bureau for the Bureau of Labor Statistics by interview and diary surveys. For more information, please visit \[insert citation for <https://www.bls.gov/cex/>\].

For selecting the endogenous and exogenous variables to simulate, choosing intuitive and strong empirical relationships is key for running the survey weight diagnostic tests. WHYY? Many diagnostic tests assume the unweighted exogenous variables $\vec{X}$ are a significant predictor of the endogenous variable $Y$.  

talk about data
talk about tests themselves

Constructing survey weights begin with first determining the selection probability of an unit being selected from the population. Let $\pi_{Si} = \mathbb{P}(i \in S)$ be the selection probability of surveying observation $i$ from sample $S$. The classic Horvitz-Thompson (HT) estimator of the population total $Y$ is defined as $\hat{Y} = \sum_{i \in S} w_{Si} y_i$ where weight $w_{Si} = \pi_{Si}^{-1}$. In case of non-response, the HT estimator can be further generalized by replacing $w_{Si}$ with $w_i = \pi_i^{-1}$ and $\pi_{i} = \mathbb{P}(i \in S, i \in F, i \in R)$ with $F$ being the units in the target population within the sampling frame and $R$ being the units in $S$ that respond to the survey.

Since survey weights are used when there is some sort of sampling bias, design-based inference is primarily used in diagnostic tests to accommodate for departures from some model assumptions and complex sampling methods. For design-based inference, consider a finite population $U$ with $n$ cases. Then the population linear regression is 

\begin{equation}
    \vec{Y} = X \vec{\beta} + \vec{\epsilon},
\end{equation}

where $\vec{Y}$ is a $n \times 1$ vector for the response variable, $X$ is a $n \times k$ matrix of explanatory $k$ variables, $\vec{\beta}$ is a $k \times 1$ vector of the coefficients, and lastly $\vec{\epsilon}$ is a $n \times 1$ vector of residual errors. \\

Recall that for linear regressions, $$\text{OLS Coefficients: } B = {(X^{T} X)^{-1}  X^{'} \vec{Y} \text{ and }  \text{Residuals: } \vec{\epsilon} = \vec{Y} - X \vec{\beta}.$$

Now, suppose a sample $S$ of $n$ units is drawn from the population $U$ where $P_i$ is the probability that the $i$th population unit is selected for the sample for $i \in \{1, ..., n\}$. Note that this probability can be further generalized to account for nonresponse and additional complex sampling characteristics. \\

Pfeffermann and Sverchov (2009) show that a design-consistent estimator of $\vec{\beta}$ is $$\hat{\vec{\beta}} = (X^T W X)^{-1} X^T W \vec{Y}$$ where ${\bf W}$ is a $n \times n$ matrix with $w_j = P_i^{-1}$ is along the diagonal. $\hat{\vec{\beta}}$ is a consistent estimator of $\vec{\beta}$ if and only if $$\text{Cov}(w_j, y_j \mid x_j) = 0,  \text{ or equivocally, } \hspace{4 pt} \mathbb{E}(y_j \mid x_j) = \mathbb{E}(w_j y_j \mid x_j).$$ 

### Model-Based Inference
Take the same linear regression setup as stated in (1). In model-based inference, additional assumptions are imposed about the error such that it is a random variable with the properties:

\begin{enumerate}
    \item $E(\vec{\epsilon}) = 0$
    \item $E(\vec{\epsilon}^{T} \vec{\epsilon}) = \sigma^2 I$
    \item $\vec{\epsilon} \perp\!\!\!\!\perp X$
\end{enumerate}

These assumptions state that as a random variable, $\vec{\epsilon}$ has mean of zero, homoscedasticity and no correlation with $X$, and is distributed independently from the explanatory variables $X$. These assumptions state that OLS $\hat{\vec{\beta}}$ is consistent, but not necessarily unbiased such that $E(\hat{\vec{\beta}}) \neq \vec{\beta}$ for finite samples, though is asymptotically unbiased. Typically the assumptions are relaxed above for model-based inferences.

### Diagnostic Tests
There is a wide variety of diagnostic tests for survey weights, yet little is know about how they adapt to certain sampling conditions and which methods are superior in determing survey weights necessity for analysis and inference. Nearly all survey weight diagnostic tests are categorized into two groups: Difference in Coefficients (DC) test and Weight Association (WA) tests. Though Bollen et al. prove that the tests are mathematically equivalent asymptotically, the tests vary depending on the finite population sampling methods. 

#### Difference in Coefficients Tests
DC tests compare the estimated coefficients of the weighted and unweighted analyses and analyze whether the coefficient estimates difference is statistically significantly different from zero. Take the same regression as stated in (1) while assuming $$E(\vec{\epsilon} \mid X) = 0 \text{ and } \text{Var}(\vec{\epsilon} \mid X) = \sigma^2 I.$$

Pfeffermann (1993) suggests an adaptation to Hausman test where with two regressions, one with weighted covariates and the other with unweighted covariates, and testing the difference of the coefficient estimates using a $\chi_{k}^2$ test with $k = \text{dim}(\hat{\vec{\beta}}_1 - \hat{\vec{\beta}}_2)$ degrees of freedom. Let $\hat{\vec{\beta}}_1$ be the weighted vector of coefficient estimates and $\hat{\vec{\beta}}_2$ be the nonweighted vector of coefficient estimates.

#### Weight Association Tests
The majority of WA tests regress unweighted and weighted covariates on the dependent variable. Hausman (1978) suggests running the regression equation $$\vec{Y} = X \vec{\beta} + X_w \vec{\beta}_w + \vec{\epsilon}$$ where $X_w$ is the weighted covariates of $X$. Hausman then suggests an $F$-test of $H_0: \vec{\beta}_w = 0$ as a test of misspecification which assumes $\vec{\epsilon}$ is Normally distributed.