---
title: "CE Exploration"
format: pdf
editor: visual
---

## Senior Thesis - Data Exploration

```{r, warning= FALSE, message = FALSE}
# Load packages
if (!require(survey)) install.packages("survey"); library(survey)
if (!require(tidyverse)) install.packages("tidyverse"); library(tidyverse)
if (!require(rpms)) install.packages("rpms"); library(rpms)
if (!require(sampling)) install.packages("sampling"); library(sampling)
if (!require(ipumsr)) install.packages("ipumsr"); library(ipumsr)
if (!require(cpsR)) install.packages("cpsR"); library(cpsR)
if (!require(NHANES)) install.packages("NHANES"); library(NHANES)
```

### CE Dataset

```{r}
CE = CE 

ce = rpms::CE %>%
  filter(TOTEXPCQ > 0 & FINCBTAX > 0 & !is.na(REGION)) %>% # Restrict greater than 0
  filter(FINCBTAX != 1259) %>% # Remove Bottom coded tax
  filter(SALARYX < 250000 & SALARYX > 0)

ggplot(ce, aes(x = log(TOTEXPCQ), y = log(FINCBTAX))) +
  geom_point(alpha = 0.05) + 
  geom_smooth(method = "lm", color = "red") + 
  geom_smooth(method = "lm", aes(weight = FINLWT21))

ce %>% summarize(across(everything(), ~ sum(is.na(.))))

table(ce$CID)
```

### API

```{r}
# Simple data visuals and regression

data(api)

ggplot(apipop, aes(api99, api00)) + 
  geom_point() + 
  geom_smooth(method = "lm") + 
  geom_abline(slope = 1, intercept = 0, color = "red")


lm1 = lm(api00 ~ api.stu, data = apipop)
summary(lm1)
```

```{r}
table(apipop$cnum) # Good to use strata and cluster from!
table(apipop$dnum)
```

```{r}
# Clean data
api = apipop |>
  select(cds, stype, name, snum, dnum, cnum, pcttest, api00, api99,
         meals, ell, mobility, avg.ed, full, enroll, api.stu)


filter(api, is.na(avg.ed))

summary(apipop$col.grad)


summary(api)
```

### NHANES

```{r}
ggplot(filter(NHANES, Weight < 50), aes(x = Weight, y = Height)) + 
  geom_point() + 
  geom_smooth(method = "lm")

filter(NHANES, Weight < 50)


```
